server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index FE.html;

    gzip on;
    gzip_types text/html text/css application/javascript;

    location / {
        try_files $uri $uri/ /FE.html;
    }
}
